
package ec.edu.ups.pw59.pruebacliente;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-02-01T12:31:41.815-05:00
 * Generated source version: 3.4.4
 *
 */
public final class ServicesObra_ServicesObraPort_Client {

    private static final QName SERVICE_NAME = new QName("http://services.prueba.pw59.ups.edu.ec/", "ServicesObraService");

    private ServicesObra_ServicesObraPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServicesObraService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ServicesObraService ss = new ServicesObraService(wsdlURL, SERVICE_NAME);
        ServicesObra port = ss.getServicesObraPort();

        
        {
        System.out.println("Invoking insertarObra...");
        ec.edu.ups.pw59.pruebacliente.Obra insertar = null;
        
        insertar = new Obra();
        insertar.setCategoria("Pintura");
        insertar.setFecha("01-01-1990");
        insertar.setId(3);
        insertar.setNombre("Untitled Loss");
        
        Persona p = new Persona();
        p.setApellido("Beksinski");
        p.setCedula("0105585523");
        p.setDireccion("Polonia");
        p.setNombre("Zdzislaw");
        
        insertar.setPersona(p);
        java.lang.String _insertarObra__return = port.insertarObra(insertar);
        System.out.println("insertarObra.result=" + insertar);


        }
        
        
        {
        System.out.println("Invoking getObra...");
        java.util.List<ec.edu.ups.pw59.pruebacliente.Obra> obtener = port.getObra();
        System.out.println("getObra.result=" + obtener);


        }

        System.exit(0);
    }

}
