package ec.edu.ups.pw59.pruebacliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2022-02-01T12:31:41.888-05:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "ServicesObraService",
                  wsdlLocation = "http://localhost:8080/prueba/ServicesObra?wsdl",
                  targetNamespace = "http://services.prueba.pw59.ups.edu.ec/")
public class ServicesObraService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.prueba.pw59.ups.edu.ec/", "ServicesObraService");
    public final static QName ServicesObraPort = new QName("http://services.prueba.pw59.ups.edu.ec/", "ServicesObraPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/prueba/ServicesObra?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicesObraService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/prueba/ServicesObra?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicesObraService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicesObraService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicesObraService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServicesObraService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicesObraService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicesObraService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServicesObra
     */
    @WebEndpoint(name = "ServicesObraPort")
    public ServicesObra getServicesObraPort() {
        return super.getPort(ServicesObraPort, ServicesObra.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicesObra
     */
    @WebEndpoint(name = "ServicesObraPort")
    public ServicesObra getServicesObraPort(WebServiceFeature... features) {
        return super.getPort(ServicesObraPort, ServicesObra.class, features);
    }

}
